name: Deploy Frontend
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t davidstna/reactapp-docker -f Dockerfile.dev .

      - name: Run Tests
        run: docker run davidstna/reactapp-docker yarn test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: reactapp-docker
          environment_name: Reactapp-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-771629859941
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip